{"name": "Проверка создания курьера с уже существующим логином", "status": "passed", "description": "При создании курьера с уже существующим логином приходит ошибка. Проверяем соответствующий код и тело ответа", "start": 1720026123548, "stop": 1720026123961, "uuid": "ec4c07fe-737e-4047-aa3e-2521e158d9ff", "historyId": "d80aec57513bc8e12718a94cca191fac", "testCaseId": "d80aec57513bc8e12718a94cca191fac", "fullName": "tests.test_create_courier.TestsCreateCourier#test_create_courier_with_login_is_exists", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestsCreateCourier"}, {"name": "host", "value": "DESKTOP-U9M0S31"}, {"name": "thread", "value": "5252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}