{"name": "Проверка авторизации курьера с неверным паролем", "status": "passed", "description": "Проверяем, что при отправке запроса с неверным паролем приходит ошибка", "start": 1720026148120, "stop": 1720026148202, "uuid": "3df75dd0-461a-40bc-beaf-e83bd1592313", "historyId": "bd48d988847780c1ff679361d461d928", "testCaseId": "bd48d988847780c1ff679361d461d928", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_wrong_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-U9M0S31"}, {"name": "thread", "value": "5252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}